// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQKGJvgMVlG7ETwdebupnxoDzYX53DDf4',
    appId: '1:29321473892:web:8d4c218180a9ae8ac89471',
    messagingSenderId: '29321473892',
    projectId: 'authkonfiapp',
    authDomain: 'authkonfiapp.firebaseapp.com',
    storageBucket: 'authkonfiapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUilALvFHiQ5Gnn6HZf9Weo2srDGBhFW4',
    appId: '1:29321473892:android:1ad8759a6d2d9327c89471',
    messagingSenderId: '29321473892',
    projectId: 'authkonfiapp',
    storageBucket: 'authkonfiapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvHrlMv2NbKOuwGsRbLrKFCeh-A-m8Hqo',
    appId: '1:29321473892:ios:47d681a23ef77d7cc89471',
    messagingSenderId: '29321473892',
    projectId: 'authkonfiapp',
    storageBucket: 'authkonfiapp.appspot.com',
    androidClientId: '29321473892-72ues6lgq6ft2j58l0v5gv4q125omgve.apps.googleusercontent.com',
    iosClientId: '29321473892-mjc77fd6op59rqr55urh8fhd6rnp5697.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvHrlMv2NbKOuwGsRbLrKFCeh-A-m8Hqo',
    appId: '1:29321473892:ios:0015131d2efd0c3fc89471',
    messagingSenderId: '29321473892',
    projectId: 'authkonfiapp',
    storageBucket: 'authkonfiapp.appspot.com',
    androidClientId: '29321473892-72ues6lgq6ft2j58l0v5gv4q125omgve.apps.googleusercontent.com',
    iosClientId: '29321473892-l51i39tiog1rju6rn4o4ujkqqf72v8sb.apps.googleusercontent.com',
    iosBundleId: 'com.example.app.RunnerTests',
  );
}
